---
title: P
---

{% extends '../../../../../../project/templates/default/default.html.swig' %}
{% block content %}

  <aside>
    <h3 class="aside__title">Paragraph</h3>
    <div class="box">
      <p>
        Hello, I'm a designer and developer creating user interfaces and experiences for the web.
      </p>

      <p>
        Lately I've been working on design, front–end and Wordpress projects with clients around the world.
      </p>
    </box>
  </aside>
{% endblock %}
