---
title: ul
---

{% extends '../../../../../../project/templates/default/default.html.swig' %}
{% block content %}

  <aside class="example__aside">
    <h3 class="aside__title">List</h3>
    <div class="box">
      <ul>
        <li>Identity design</li><li>Responsive web design</li><li>Front–end development</li><li>Styleguide</li><li>Wordpress</li><li>Storytelling</li><li>E–commerce</li>
      </ul>
    </div>
  </aside>
{% endblock %}
