---
title: Flip
---

{% extends '../../../../project/templates/default/default.html.swig' %}
{% block content %}

  <aside class="aside">
    <h3 class="aside__title">Flip</h3>

    <div class="box">
      <a class="link" href="#" title="This is a link with flip. Try hover or click."><span data-hover="This is a link with flip. Try hover or click.">This is a link with flip. Try hover or click.</span></a>
    </div>
  </aside>

{% endblock %}
