<article class="contact__form">
  <h3>Contact form</h3>

  <p>
    Send me an automatic email and I'll get back to you.
  </p>

  <form action="https://getsimpleform.com/messages?form_api_token=d880283125ae9e07ca71d96259d6647b" method="post">
    <!-- all your input fields here.... -->
    <input type='text' name='email' placeholder="Your email"/>
    <input type='submit' value='Send email' />
  </form>
</article>
