---
title: Uppercase
---

{% extends '../../../../../../project/templates/default/default.html.swig' %}
{% block content %}

  <aside>
    <h3 class="aside__title">Uppercase</h3>
    <div class="box example-1">
      This is an uppercase text with proper letter spacing.
    </div>
  </aside>

  <aside>
    <h3 class="aside__title">Browser default Uppercase</h3>
    <div class="box example-2">
      This is an uppercase text with no extra letter spacing.
    </div>
  </aside>
{% endblock %}
