<ul>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
Project</div>
<ul>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="About" href="{{ site.url }}project/about">About</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Header" href="{{ site.url }}project/header">Header</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Links" href="{{ site.url }}project/links">Links</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
Templates</div>
<ul>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Default" href="{{ site.url }}project/templates/default">Default</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Head" href="{{ site.url }}project/templates/head">Head</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Scripts" href="{{ site.url }}project/templates/scripts">Scripts</a>
</li>
</ul>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Thumb" href="{{ site.url }}project/thumb">Thumb</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
Values</div>
<ul>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Front end" href="{{ site.url }}project/values/__front-end">Front end</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Styleguide" href="{{ site.url }}project/values/__styleguide">Styleguide</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Ui" href="{{ site.url }}project/values/__ui">Ui</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Wordpress" href="{{ site.url }}project/values/__wordpress">Wordpress</a>
</li>
</ul>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
Work</div>
<ul>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Description" href="{{ site.url }}project/work/__description">Description</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Images" href="{{ site.url }}project/work/__images">Images</a>
</li>
<li>
<div>
{% include '../../../../../site/components/framework/design/decorations/long-dash/long-dash.html.swig' %}
<a class="link" title="Services" href="{{ site.url }}project/work/__services">Services</a>
</li>
</ul>
</li>
</ul>
</li>
</ul>